### ISSUE TITLE
[ENHANCEMENT] 能否推出服务端整合包

### ISSUE THREAD

**Issue by FxRayHughes** [ProjectHDS/Herodotus#26]
**你所请求添加的特性是否与一个问题关联?**
简单明了的回答问题 [如 否/没有加速火把我觉得玩不下去]

**描述你需要的新特性**
简单明了的描述你想请求的新特性

**环境信息(请补全以下信息):**
 - 操作系统: [如Windows 10, macOS BigSur]
 - 分配内存: [如8GGB, 6000MB]
 - 整合版本: [如1.0.0, 1.0.2]

**附加信息**
添加你认为可以帮助理解此请求的相关的附加描述或截图

**Comment by GBLodb** [comment]
由于 CurseForge 推出新 API, 旧的下载模组的 cli 工具基本失效, 于是暂停了相关自动打包流程. 在 [CurseMaven](https://www.cursemaven.com/) 项目或 [ModPackDownloader](https://github.com/Nincraft/ModPackDownloader) 更新后, 会再考虑更新修复相关自动打包流程. 此外, 尽管 HDS 对服务端没有硬性要求, 因为一些附属模组的兼容性问题和内容模组在曾经测试中存在的问题, 依然建议使用 Forge 官方服务端核心, 以后的自动打包流程也将坚持这一点, 以上.

**Comment by GBLodb** [comment]
从 [v0.3.0.783](https://github.com/ProjectHDS/Herodotus/releases/tag/v0.3.0.783) 起，开始提供服务端打包。
