### ISSUE TITLE
[BUG] 点燃树叶后掉落木棍

### ISSUE THREAD

**Issue by sfjdh** [ProjectHDS/Herodotus#30]
**描述问题**
点燃树叶后掉落木棍。
**期望现象**
树叶燃烧后不会掉落木棍
**环境信息(请补全以下信息):**
 - 操作系统: [Windows 11]
- 整合版本: [0.3.0.848]

**Comment by RisingInIris2017** [comment]
你好！我是 Project Herodotus 策划团队成员 RisingInIris2017.
经策划团队讨论，对你的问题答复如下：

在 Herodotus 整合包的游戏流程中，并未给“木棍的获取”设置任何障碍。
如果一定要通过火烧树叶来获取木棍，
要么期待在存档开始时，就出生在靠近森林的熔岩湖附近，要么等待闪电；
要么你已经获得了可以点燃火焰的道具，这个时候木棍已经是一种很容易获得的廉价材料了。

本着“绝对不在不必要的地方设置障碍”的原则，
我们一致认同“树叶被烧毁时掉落木棍”是一个无关紧要的游戏特性。

但我们非常期待你可以给出一个，你认为这个特性应当被禁止的理由，
这对于 Herodotus 的设计非常重要，我们也对你提供的建议表示由衷感谢。

**Comment by sfjdh** [comment]
这是否会对服务器性能造成额外负担，尤其是性能不佳的电脑？

**Comment by GBLodb** [comment]
> 这是否会对服务器性能造成额外负担，尤其是性能不佳的电脑？

涉及到区块加载问题和物品实体性能问题, 造成的额外负担实际上是微乎其微的
