### ISSUE TITLE
[BUG] 添加枯死木→橡木木板配方

### ISSUE THREAD

**Issue by cneicy** [ProjectHDS/Herodotus#31]
**描述问题**
bop模组的垂死木DeadWood没有对应的木板，故火种科技砧板无垂死木到木板的配方。

**期望现象**
T1下新建choppingBlock.zs以为此单独添加到橡木木板的配方。

**环境信息(请补全以下信息):**
 - 整合版本: [0.3.0.851]

**附加信息**
已经在本地新建脚本正在测试可用性，证实可用后会开启PR。

**Comment by GBLodb** [comment]
The use of Dead Wood is not considered, so it is not a bug.

枯死木的使用不在考虑之中，故无法合成木板不属于 bug。

Content about the compatibility of BOP with Pyrotech is managed by [hds_main/utils/bopCompat.zs](https://github.com/ProjectHDS/Herodotus/blob/release/.minecraft/scripts/hds_main/utils/bopCompat.zs).

有关 Biomes O' Plenty 与 PyroTech 兼容的内容均由 [hds_main/utils/bopCompat.zs](https://github.com/ProjectHDS/Herodotus/blob/release/.minecraft/scripts/hds_main/utils/bopCompat.zs) 统管。

To sum up, close the associated pull request at the same time.

综上所述，同时关闭相关联的拉取请求。
