### ISSUE TITLE
[BUG] Defaults to non-English language, breaking JEI

### ISSUE THREAD

**Issue by Thelk641** [ProjectHDS/Herodotus#33]
**Describe the bug**
The modpack being, by default, in a non-English language makes it pretty hard for anybody who doesn't speak the language to actually play it. Changing the language for the game in the main menu (something that seems to have to be done every time the game is launched) makes most of the menus and item names readable, but it doesn't solve everything. Something as simple as searching "granite" or "worktable" in JEI doesn't find anything relevant, probably because these are not the actual names of these items. Also the name for things like "worktable" is only translated in the side-bar of crafting recipe but not in the tab's name.

Other things are left untranslated such as tips during the loading screen, but these don't really impact gameplay.

**To Reproduce**
Just install the modpack via CurseForge.

**Expected behavior**
The modpack is entirely playable in the default language for this game.

![Screenshot_188](https://user-images.githubusercontent.com/39498071/187007405-75e05359-b805-4487-ba82-273fe4a9109e.png)
![Screenshot_187](https://user-images.githubusercontent.com/39498071/187007408-3eaab90f-7a75-4079-8e30-6de0d1bead68.png)
.

**Comment by RisingInIris2017** [comment]
Fixed by 897a915.
Thanks for your feedback!
