### ISSUE TITLE
Everything is in Chinese/Japanese

### ISSUE THREAD

**Issue by openblocki** [ProjectHDS/Herodotus#35]
When you first Start up the Pack everything is in ~~Bing Chilling~~ Chinese, Problem is: Most People that wanna play this pack probably cant read that, kinda annoying tbh

**Comment by GBLodb** [comment]
Thanks for reporting, duplicate with #33.

I18nUpdateMod will no longer come with the pack in the future, if you have trouble language set to Chinese every startup, please try disable I18nUpdateMod. Sorry for the trouble.

**Comment by ChromaPIE** [comment]
also that joke was so dead and not funny so next time if you wanna put a delete line on smth just delete it. appeciate that.
