### ISSUE TITLE
[BUG] Quest Descriptions Wrong

### ISSUE THREAD

**Issue by openblocki** [ProjectHDS/Herodotus#36]
In the Tab Ore Processing the Quest Descriptions are wrong, as far as my knowledge goes. Either that or something went wrong with the ore generation.
Says:
Yellow ore spawns with Sphere ores
Blue Ore spawns with Square ores
Red ore spawns with Rhombus ores

Instead:
Yellow Ore spawns with Rhombus Ores.
Blue Ore spawns with Spherical Ores.
Red Ore spawns with Square Ores.

**Comment by GBLodb** [comment]
Yeeeah I do believe I forgot about to fix this, thanks for reporting.

**Comment by GBLodb** [comment]
Fixed in dev branch.
